// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_byCCNW4uO4QJTf-KHc467qrp_61IWT0',
    appId: '1:570612700152:android:e95cfc6bc88ceb1e8e7c0d',
    messagingSenderId: '570612700152',
    projectId: 'summerclass-3c1db',
    storageBucket: 'summerclass-3c1db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApVOUzySZQlzLwqU6ZGwvA4SCI8ymjkCE',
    appId: '1:570612700152:ios:004c2b53b80020ff8e7c0d',
    messagingSenderId: '570612700152',
    projectId: 'summerclass-3c1db',
    storageBucket: 'summerclass-3c1db.appspot.com',
    androidClientId: '570612700152-e50nf4sfqg4nr7vhg1majd27m8bjegh4.apps.googleusercontent.com',
    iosClientId: '570612700152-b2gaaqm3g8ppvdkomgod56ngfbc397u5.apps.googleusercontent.com',
    iosBundleId: 'com.example.summerclass2024',
  );
}
